/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package org.itenas.oop.project.component;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import org.itenas.oop.project.connection.ConnectionManager;

/**
 *
 * @author aryan
 */
public class DashboardAdmin extends javax.swing.JPanel {
    private ConnectionManager conMan;
    private Connection conn;
    Statement stmt;
    ResultSet rs;
    
    public DashboardAdmin() {
        initComponents();
        menarikData();
    }
    
    private void menarikData() {
        conMan = new ConnectionManager();
        conn = conMan.connectDb();
        Statement stmt = null;
        ResultSet rs = null;
        try {
            stmt = conn.createStatement();

            String queryAdmin = "SELECT COUNT(*) AS jumlah FROM daftar_akun WHERE jenis_akun = 'Admin'";
            rs = stmt.executeQuery(queryAdmin);
            if (rs.next()) {
                txtSumAdmin.setText(String.valueOf(rs.getInt("jumlah")));
            }
           
            String queryPendaftar = "SELECT COUNT(*) AS jumlah FROM daftar_pendaftar_magang";
            rs = stmt.executeQuery(queryPendaftar);
            if (rs.next()) {
                txtSumPendaftar.setText(String.valueOf(rs.getInt("jumlah")));
            }

            String queryPenyelenggara = "SELECT COUNT(*) AS jumlah FROM daftarpenyelenggara";
            rs = stmt.executeQuery(queryPenyelenggara);
            if (rs.next()) {
                txtSumPenyelenggara.setText(String.valueOf(rs.getInt("jumlah")));
            }

            String queryMagang = "SELECT COUNT(*) AS jumlah FROM daftar_magang";
            rs = stmt.executeQuery(queryMagang);
            if (rs.next()) {
                txtSumMagang.setText(String.valueOf(rs.getInt("jumlah")));
            }

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error saat menarik data: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
        try {
            if (rs != null) {
                rs.close();
            }
            if (stmt != null) {
                stmt.close();
            }
        } catch (SQLException ex) {
            System.out.println("Error saat menutup resources: " + ex.getMessage());
        }
    }

  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cardMagang1 = new org.itenas.oop.project.component.CardMagang();
        txtDaftarAdmin = new javax.swing.JLabel();
        txtSumAdmin = new javax.swing.JLabel();
        cardMagang2 = new org.itenas.oop.project.component.CardMagang();
        txtDaftarPenyelenggara = new javax.swing.JLabel();
        txtSumPenyelenggara = new javax.swing.JLabel();
        cardMagang3 = new org.itenas.oop.project.component.CardMagang();
        txtDaftarPendaftar = new javax.swing.JLabel();
        txtSumPendaftar = new javax.swing.JLabel();
        cardMagang4 = new org.itenas.oop.project.component.CardMagang();
        txtDaftarMagang = new javax.swing.JLabel();
        txtSumMagang = new javax.swing.JLabel();

        setBackground(new java.awt.Color(239, 236, 229));

        txtDaftarAdmin.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtDaftarAdmin.setForeground(new java.awt.Color(51, 51, 51));
        txtDaftarAdmin.setText("Jumlah daftar Admin");
        txtDaftarAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtDaftarAdminMouseClicked(evt);
            }
        });

        txtSumAdmin.setFont(new java.awt.Font("Segoe UI", 0, 50)); // NOI18N
        txtSumAdmin.setForeground(new java.awt.Color(51, 51, 51));
        txtSumAdmin.setText("SUM");

        javax.swing.GroupLayout cardMagang1Layout = new javax.swing.GroupLayout(cardMagang1);
        cardMagang1.setLayout(cardMagang1Layout);
        cardMagang1Layout.setHorizontalGroup(
            cardMagang1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardMagang1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cardMagang1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDaftarAdmin)
                    .addComponent(txtSumAdmin))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        cardMagang1Layout.setVerticalGroup(
            cardMagang1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardMagang1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(txtDaftarAdmin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSumAdmin)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        txtDaftarPenyelenggara.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtDaftarPenyelenggara.setForeground(new java.awt.Color(51, 51, 51));
        txtDaftarPenyelenggara.setText("Jumlah daftar Penyelenggara");
        txtDaftarPenyelenggara.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtDaftarPenyelenggaraMouseClicked(evt);
            }
        });

        txtSumPenyelenggara.setFont(new java.awt.Font("Segoe UI", 0, 50)); // NOI18N
        txtSumPenyelenggara.setForeground(new java.awt.Color(51, 51, 51));
        txtSumPenyelenggara.setText("SUM");

        javax.swing.GroupLayout cardMagang2Layout = new javax.swing.GroupLayout(cardMagang2);
        cardMagang2.setLayout(cardMagang2Layout);
        cardMagang2Layout.setHorizontalGroup(
            cardMagang2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardMagang2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cardMagang2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDaftarPenyelenggara)
                    .addComponent(txtSumPenyelenggara))
                .addContainerGap(76, Short.MAX_VALUE))
        );
        cardMagang2Layout.setVerticalGroup(
            cardMagang2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardMagang2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(txtDaftarPenyelenggara)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSumPenyelenggara)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        txtDaftarPendaftar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtDaftarPendaftar.setForeground(new java.awt.Color(51, 51, 51));
        txtDaftarPendaftar.setText("Jumlah daftar Pendaftar");

        txtSumPendaftar.setFont(new java.awt.Font("Segoe UI", 0, 50)); // NOI18N
        txtSumPendaftar.setForeground(new java.awt.Color(51, 51, 51));
        txtSumPendaftar.setText("SUM");

        javax.swing.GroupLayout cardMagang3Layout = new javax.swing.GroupLayout(cardMagang3);
        cardMagang3.setLayout(cardMagang3Layout);
        cardMagang3Layout.setHorizontalGroup(
            cardMagang3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardMagang3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cardMagang3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDaftarPendaftar)
                    .addComponent(txtSumPendaftar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        cardMagang3Layout.setVerticalGroup(
            cardMagang3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardMagang3Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(txtDaftarPendaftar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSumPendaftar)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        txtDaftarMagang.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtDaftarMagang.setForeground(new java.awt.Color(51, 51, 51));
        txtDaftarMagang.setText("Jumlah daftar Magang");
        txtDaftarMagang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtDaftarMagangMouseClicked(evt);
            }
        });

        txtSumMagang.setFont(new java.awt.Font("Segoe UI", 0, 50)); // NOI18N
        txtSumMagang.setForeground(new java.awt.Color(51, 51, 51));
        txtSumMagang.setText("SUM");

        javax.swing.GroupLayout cardMagang4Layout = new javax.swing.GroupLayout(cardMagang4);
        cardMagang4.setLayout(cardMagang4Layout);
        cardMagang4Layout.setHorizontalGroup(
            cardMagang4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardMagang4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cardMagang4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDaftarMagang)
                    .addComponent(txtSumMagang))
                .addContainerGap(134, Short.MAX_VALUE))
        );
        cardMagang4Layout.setVerticalGroup(
            cardMagang4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardMagang4Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(txtDaftarMagang)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSumMagang)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cardMagang1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cardMagang4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(cardMagang3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cardMagang2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(33, 33, 33))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cardMagang1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cardMagang2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cardMagang4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cardMagang3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(260, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtDaftarAdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtDaftarAdminMouseClicked
        // TODO add your handling code here:
        new MelihatDaftarAdmin().setVisible(true);
    }//GEN-LAST:event_txtDaftarAdminMouseClicked

    private void txtDaftarPenyelenggaraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtDaftarPenyelenggaraMouseClicked
        // TODO add your handling code here:
        new MelihatDaftarPenyelenggara().setVisible(true);
    }//GEN-LAST:event_txtDaftarPenyelenggaraMouseClicked

    private void txtDaftarMagangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtDaftarMagangMouseClicked
        // TODO add your handling code here:
        new MelihatDaftarPenyelenggara().setVisible(true);
    }//GEN-LAST:event_txtDaftarMagangMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.itenas.oop.project.component.CardMagang cardMagang1;
    private org.itenas.oop.project.component.CardMagang cardMagang2;
    private org.itenas.oop.project.component.CardMagang cardMagang3;
    private org.itenas.oop.project.component.CardMagang cardMagang4;
    private javax.swing.JLabel txtDaftarAdmin;
    private javax.swing.JLabel txtDaftarMagang;
    private javax.swing.JLabel txtDaftarPendaftar;
    private javax.swing.JLabel txtDaftarPenyelenggara;
    private javax.swing.JLabel txtSumAdmin;
    private javax.swing.JLabel txtSumMagang;
    private javax.swing.JLabel txtSumPendaftar;
    private javax.swing.JLabel txtSumPenyelenggara;
    // End of variables declaration//GEN-END:variables
}
