/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package org.itenas.oop.project.component;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import org.itenas.oop.project.connection.ConnectionManager;

/**
 *
 * @author aryan
 */
public class DashboardAdmin extends javax.swing.JPanel {
    private ConnectionManager conMan;
    private Connection conn;
    Statement stmt;
    ResultSet rs;
    
    public DashboardAdmin() {
        initComponents();
        menarikData();
    }
    
    private void menarikData() {
        conMan = new ConnectionManager();
        conn = conMan.connectDb();
        Statement stmt = null;
        ResultSet rs = null;
        try {
            stmt = conn.createStatement();

            String queryAdmin = "SELECT COUNT(*) AS jumlah FROM daftar_akun WHERE jenis_akun = 'Admin'";
            rs = stmt.executeQuery(queryAdmin);
            if (rs.next()) {
                txtSumAdmin.setText(String.valueOf(rs.getInt("jumlah")));
            }
           
            String queryPendaftar = "SELECT COUNT(*) AS jumlah FROM daftar_pendaftar_magang";
            rs = stmt.executeQuery(queryPendaftar);
            if (rs.next()) {
                txtSumPendaftar.setText(String.valueOf(rs.getInt("jumlah")));
            }

            String queryPenyelenggara = "SELECT COUNT(*) AS jumlah FROM daftarpenyelenggara";
            rs = stmt.executeQuery(queryPenyelenggara);
            if (rs.next()) {
                txtSumPenyelenggara.setText(String.valueOf(rs.getInt("jumlah")));
            }

            String queryMagang = "SELECT COUNT(*) AS jumlah FROM daftar_magang";
            rs = stmt.executeQuery(queryMagang);
            if (rs.next()) {
                txtSumMagang.setText(String.valueOf(rs.getInt("jumlah")));
            }

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error saat menarik data: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
        try {
            if (rs != null) {
                rs.close();
            }
            if (stmt != null) {
                stmt.close();
            }
        } catch (SQLException ex) {
            System.out.println("Error saat menutup resources: " + ex.getMessage());
        }
    }

  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtDaftarAdmin = new javax.swing.JLabel();
        txtSumAdmin = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txtDaftarPenyelenggara = new javax.swing.JLabel();
        txtSumPenyelenggara = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        txtDaftarMagang = new javax.swing.JLabel();
        txtSumMagang = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        txtDaftarPendaftar = new javax.swing.JLabel();
        txtSumPendaftar = new javax.swing.JLabel();

        setBackground(new java.awt.Color(239, 236, 229));

        jPanel1.setBackground(new java.awt.Color(146, 180, 236));

        txtDaftarAdmin.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtDaftarAdmin.setForeground(new java.awt.Color(51, 51, 51));
        txtDaftarAdmin.setText("Jumlah daftar Admin");
        txtDaftarAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtDaftarAdminMouseClicked(evt);
            }
        });

        txtSumAdmin.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        txtSumAdmin.setForeground(new java.awt.Color(51, 51, 51));
        txtSumAdmin.setText("SUM");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDaftarAdmin)
                    .addComponent(txtSumAdmin))
                .addContainerGap(73, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(txtDaftarAdmin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(txtSumAdmin)
                .addGap(18, 18, 18))
        );

        jPanel2.setBackground(new java.awt.Color(146, 180, 236));
        jPanel2.setPreferredSize(new java.awt.Dimension(261, 164));

        txtDaftarPenyelenggara.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtDaftarPenyelenggara.setForeground(new java.awt.Color(51, 51, 51));
        txtDaftarPenyelenggara.setText("Jumlah daftar Penyelenggara");
        txtDaftarPenyelenggara.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtDaftarPenyelenggaraMouseClicked(evt);
            }
        });

        txtSumPenyelenggara.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        txtSumPenyelenggara.setForeground(new java.awt.Color(51, 51, 51));
        txtSumPenyelenggara.setText("SUM");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDaftarPenyelenggara)
                    .addComponent(txtSumPenyelenggara))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(txtDaftarPenyelenggara)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(txtSumPenyelenggara)
                .addGap(17, 17, 17))
        );

        jPanel3.setBackground(new java.awt.Color(146, 180, 236));
        jPanel3.setPreferredSize(new java.awt.Dimension(261, 164));

        txtDaftarMagang.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtDaftarMagang.setForeground(new java.awt.Color(51, 51, 51));
        txtDaftarMagang.setText("Jumlah daftar Magang");
        txtDaftarMagang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtDaftarMagangMouseClicked(evt);
            }
        });

        txtSumMagang.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        txtSumMagang.setForeground(new java.awt.Color(51, 51, 51));
        txtSumMagang.setText("SUM");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDaftarMagang)
                    .addComponent(txtSumMagang))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(txtDaftarMagang)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtSumMagang)
                .addGap(14, 14, 14))
        );

        jPanel4.setBackground(new java.awt.Color(146, 180, 236));
        jPanel4.setPreferredSize(new java.awt.Dimension(261, 164));

        txtDaftarPendaftar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtDaftarPendaftar.setForeground(new java.awt.Color(51, 51, 51));
        txtDaftarPendaftar.setText("Jumlah daftar Pendaftar");

        txtSumPendaftar.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        txtSumPendaftar.setForeground(new java.awt.Color(51, 51, 51));
        txtSumPendaftar.setText("SUM");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDaftarPendaftar)
                    .addComponent(txtSumPendaftar))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(txtDaftarPendaftar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(txtSumPendaftar)
                .addGap(17, 17, 17))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 129, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(76, 76, 76)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(233, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtDaftarAdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtDaftarAdminMouseClicked
        // TODO add your handling code here:
        new MelihatDaftarAdmin().setVisible(true);
    }//GEN-LAST:event_txtDaftarAdminMouseClicked

    private void txtDaftarPenyelenggaraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtDaftarPenyelenggaraMouseClicked
        // TODO add your handling code here:
        new MelihatDaftarPenyelenggara().setVisible(true);
    }//GEN-LAST:event_txtDaftarPenyelenggaraMouseClicked

    private void txtDaftarMagangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtDaftarMagangMouseClicked
        // TODO add your handling code here:
        new MelihatDaftarPenyelenggara().setVisible(true);
    }//GEN-LAST:event_txtDaftarMagangMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel txtDaftarAdmin;
    private javax.swing.JLabel txtDaftarMagang;
    private javax.swing.JLabel txtDaftarPendaftar;
    private javax.swing.JLabel txtDaftarPenyelenggara;
    private javax.swing.JLabel txtSumAdmin;
    private javax.swing.JLabel txtSumMagang;
    private javax.swing.JLabel txtSumPendaftar;
    private javax.swing.JLabel txtSumPenyelenggara;
    // End of variables declaration//GEN-END:variables
}
