/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.itenas.oop.project.component;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import org.itenas.oop.project.connection.ConnectionManager;
import org.itenas.oop.project.model.MagangPendaftar;
import org.itenas.oop.project.repository.ControllerPendaftar;

/**
 *
 * @author aryan
 */
public class SeleksiPendaftarFrame extends javax.swing.JFrame {
    Boolean hasil;
    ControllerPendaftar conPendaftar = new ControllerPendaftar();
    private ConnectionManager conMan;
    private Connection conn;
    
    /**
     * Creates new form SeleksiPendaftarForm22
     */
    public SeleksiPendaftarFrame() {
        initComponents();
        getData();
    }

    public final void getData(){
//        MagangPendaftar magangPendaftar = new MagangPendaftar();
//        magangPendaftar = conPendaftar.mencariMagangPendaftarBerdasarkanNama(namaPendaftar);
        conMan = new ConnectionManager();
        conn = conMan.connectDb();
        try{
            Statement stm = conn.createStatement();
            String query = "SELECT daftar_pendaftar_magang.nama, daftar_pendaftar_magang.jenis_kelamin, daftar_pendaftar_magang.pendidikan_saat_ini, daftar_pendaftar_magang.umur, daftar_pendaftar_magang.pengalaman_organisasi, daftar_pendaftar_magang.pengalaman_lainnya " +
                       "FROM daftar_pendaftar_magang " +
                       "INNER JOIN temp_daftar_pendaftar_magang " +
                       "ON temp_daftar_pendaftar_magang.nama = daftar_pendaftar_magang.nama;";
            ResultSet rs = stm.executeQuery(query);
            if (rs.next()){
                txtNama.setText(rs.getString("nama"));
                txtJenisKelamin.setText(rs.getString("jenis_kelamin"));
                txtPendidikanSaatIni.setText(rs.getString("pendidikan_saat_ini"));
                txtUmur.setText(rs.getString("umur"));
                txtPengalamanOrganisasi.setText(rs.getString("pengalaman_organisasi"));
                txtPengalamanLainnya.setText(rs.getString("pengalaman_lainnya"));                   
            }
        } catch (SQLException ex){
            System.out.println(ex.toString());
        }
        
    }

    public String mengambilJudul() throws SQLException{
        String judul = null;
        conMan = new ConnectionManager();     
        Connection conn = conMan.connectDb();
        Statement stm = conn.createStatement();
        ResultSet rs = stm.executeQuery("SELECT judul from temp_daftar_pendaftar_magang");        
        try {
            while (rs.next()){
                judul = rs.getString("judul");
                return judul;
            }             
        }catch(SQLException ex){
            ex.printStackTrace();
        }
        return judul;
    }     
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        textNama = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextArea();
        textNama1 = new javax.swing.JLabel();
        txtJenisKelamin = new javax.swing.JTextArea();
        textNama2 = new javax.swing.JLabel();
        txtPendidikanSaatIni = new javax.swing.JTextArea();
        txtUmur = new javax.swing.JTextArea();
        textNama3 = new javax.swing.JLabel();
        btnTerima = new javax.swing.JButton();
        btnTolak = new javax.swing.JButton();
        btnKembali = new javax.swing.JButton();
        textOrganisasi = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtPengalamanOrganisasi = new javax.swing.JTextArea();
        textPengalamanLainnya = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtPengalamanLainnya = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(239, 236, 229));

        textNama.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        textNama.setForeground(new java.awt.Color(51, 51, 51));
        textNama.setText("Nama");

        txtNama.setColumns(20);
        txtNama.setRows(5);

        textNama1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        textNama1.setForeground(new java.awt.Color(51, 51, 51));
        textNama1.setText("Jenis Kelamin");

        txtJenisKelamin.setColumns(20);
        txtJenisKelamin.setRows(5);

        textNama2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        textNama2.setForeground(new java.awt.Color(51, 51, 51));
        textNama2.setText("Pendidikan Saat Ini");

        txtPendidikanSaatIni.setColumns(20);
        txtPendidikanSaatIni.setRows(5);

        txtUmur.setColumns(20);
        txtUmur.setRows(5);

        textNama3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        textNama3.setForeground(new java.awt.Color(51, 51, 51));
        textNama3.setText("Umur");

        btnTerima.setBackground(new java.awt.Color(153, 153, 255));
        btnTerima.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnTerima.setForeground(new java.awt.Color(51, 51, 51));
        btnTerima.setText("Terima");
        btnTerima.setBorder(null);
        btnTerima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTerimaActionPerformed(evt);
            }
        });

        btnTolak.setBackground(new java.awt.Color(255, 153, 153));
        btnTolak.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnTolak.setForeground(new java.awt.Color(51, 51, 51));
        btnTolak.setText("Tolak");
        btnTolak.setBorder(null);
        btnTolak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTolakActionPerformed(evt);
            }
        });

        btnKembali.setBackground(new java.awt.Color(255, 153, 153));
        btnKembali.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnKembali.setForeground(new java.awt.Color(51, 51, 51));
        btnKembali.setText("Kembali");
        btnKembali.setBorder(null);
        btnKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliActionPerformed(evt);
            }
        });

        textOrganisasi.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        textOrganisasi.setForeground(new java.awt.Color(51, 51, 51));
        textOrganisasi.setText("Pengalaman Organisasi");

        txtPengalamanOrganisasi.setBackground(new java.awt.Color(239, 239, 239));
        txtPengalamanOrganisasi.setColumns(20);
        txtPengalamanOrganisasi.setForeground(new java.awt.Color(51, 51, 51));
        txtPengalamanOrganisasi.setRows(5);
        txtPengalamanOrganisasi.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(191, 191, 191)));
        jScrollPane2.setViewportView(txtPengalamanOrganisasi);

        textPengalamanLainnya.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        textPengalamanLainnya.setForeground(new java.awt.Color(51, 51, 51));
        textPengalamanLainnya.setText("Pengalaman Lainnya (Pekerjaan/Penghargaan/Keahlian)");

        txtPengalamanLainnya.setBackground(new java.awt.Color(239, 239, 239));
        txtPengalamanLainnya.setColumns(20);
        txtPengalamanLainnya.setForeground(new java.awt.Color(51, 51, 51));
        txtPengalamanLainnya.setRows(5);
        txtPengalamanLainnya.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(191, 191, 191)));
        jScrollPane3.setViewportView(txtPengalamanLainnya);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNama, javax.swing.GroupLayout.DEFAULT_SIZE, 706, Short.MAX_VALUE)
                    .addComponent(txtJenisKelamin, javax.swing.GroupLayout.DEFAULT_SIZE, 706, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnKembali, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnTolak, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnTerima, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtUmur, javax.swing.GroupLayout.DEFAULT_SIZE, 706, Short.MAX_VALUE)
                    .addComponent(txtPendidikanSaatIni, javax.swing.GroupLayout.DEFAULT_SIZE, 706, Short.MAX_VALUE)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textNama, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textNama1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textNama3, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textNama2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textOrganisasi, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textPengalamanLainnya, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textNama)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textNama1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtJenisKelamin, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textNama3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUmur, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textNama2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPendidikanSaatIni, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textOrganisasi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textPengalamanLainnya)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTolak, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTerima, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnKembali, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(111, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 718, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 702, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTerimaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTerimaActionPerformed
        conMan = new ConnectionManager();
        conn = conMan.connectDb();
        String nama = txtNama.getText();
        
        String judul;
        int konfirmasi = JOptionPane.showConfirmDialog(null, "Apakah Anda yakin ingin menerima pendaftar ini?", "Konfirmasi Penerimaan", JOptionPane.YES_NO_OPTION);
        if (konfirmasi == JOptionPane.YES_NO_OPTION) {  
            try {
                judul = mengambilJudul();
                try {
                    Statement stm = conn.createStatement();
                    String query2 = "INSERT INTO hasil_seleksi "
                        + "(nama, judul, status)"
                        + "values ('" + nama + "', '" + judul + "', 'Diterima')";
                    String query = "DELETE FROM temp_daftar_pendaftar_magang"
                        + " WHERE nama = '"
                        + nama + "';";
                    stm.executeUpdate(query2);            
                    stm.executeUpdate(query);
                    new SeleksiPendaftarFrame().setVisible(false); 
                    dispose();
                } catch (SQLException ex) {
                    System.out.println(ex.toString());
                }                    
            } catch (SQLException ex) {
                Logger.getLogger(SeleksiPendaftarFrame.class.getName()).log(Level.SEVERE, null, ex);
            }                     
        }        
    }//GEN-LAST:event_btnTerimaActionPerformed

    private void btnTolakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTolakActionPerformed
        conMan = new ConnectionManager();
        conn = conMan.connectDb();
        String nama = txtNama.getText();
        
        String judul;
        int konfirmasi = JOptionPane.showConfirmDialog(null, "Apakah Anda yakin ingin menolak pendaftar ini?", "Konfirmasi Penolakan", JOptionPane.YES_NO_OPTION);
        if (konfirmasi == JOptionPane.YES_NO_OPTION) {  
            try {
                judul = mengambilJudul();
                try {
                    Statement stm = conn.createStatement();
                    String query2 = "INSERT INTO hasil_seleksi "
                        + "(nama, judul, status)"
                        + "values ('" + nama + "', '" + judul + "', 'Ditolak')";
                    String query = "DELETE FROM temp_daftar_pendaftar_magang"
                        + " WHERE nama = '"
                        + nama + "';";
                    stm.executeUpdate(query2);            
                    stm.executeUpdate(query);
                    new SeleksiPendaftarFrame().setVisible(false); 
                    dispose();
                } catch (SQLException ex) {
                    System.out.println(ex.toString());
                }            
            } catch (SQLException ex) {
                Logger.getLogger(SeleksiPendaftarFrame.class.getName()).log(Level.SEVERE, null, ex);
            }                     
        }
    }//GEN-LAST:event_btnTolakActionPerformed

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
        conMan = new ConnectionManager();
        conn = conMan.connectDb();
        String nama = txtNama.getText();
        
        try {
            Statement stm = conn.createStatement();
            String query2 = "DELETE FROM temp_daftar_pendaftar_magang"
                + " WHERE nama = '"
                + nama + "';";
            stm.executeUpdate(query2);
            new SeleksiPendaftarFrame().setVisible(false);
            dispose();
        } catch (SQLException ex) {
            System.out.println(ex.toString());
        }

    }//GEN-LAST:event_btnKembaliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SeleksiPendaftarFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SeleksiPendaftarFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SeleksiPendaftarFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SeleksiPendaftarFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SeleksiPendaftarFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKembali;
    private javax.swing.JButton btnTerima;
    private javax.swing.JButton btnTolak;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel textNama;
    private javax.swing.JLabel textNama1;
    private javax.swing.JLabel textNama2;
    private javax.swing.JLabel textNama3;
    private javax.swing.JLabel textOrganisasi;
    private javax.swing.JLabel textPengalamanLainnya;
    private javax.swing.JTextArea txtJenisKelamin;
    private javax.swing.JTextArea txtNama;
    private javax.swing.JTextArea txtPendidikanSaatIni;
    private javax.swing.JTextArea txtPengalamanLainnya;
    private javax.swing.JTextArea txtPengalamanOrganisasi;
    private javax.swing.JTextArea txtUmur;
    // End of variables declaration//GEN-END:variables
}
